name: "Render"

on:
  push:
    branches:
      - master

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile cv.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cv.pdf
      - name: Commit rendered CV
        run: |
          git config --global user.name 'github-actions bot'
          git config --global user.email 'django228@users.noreply.github.com'
          git remote set-url origin https://github.com/django228/CV
          git add cv.pdf
          git commit -m "Publish rendered CV"
          git push
