name: Build PDF

on:
  push:
    branches: [ master ]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          # Optional: Add compiler arguments if needed
          args: "-shell-escape -interaction=nonstopmode -file-line-error"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV.pdf
          path: cv.pdf
